# Generated by Django 4.2 on 2024-06-04 12:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
